#!/bin/bash

#makes the necessary direcatory and moves there
mkdir "coursesFile"
cd "coursesFile"

# grabs the html and extracts all necessary codes
wget https://gitlab.fit.cvut.cz/barinkl/bi-ps2-public/raw/master/edux/index.html -q -O - | grep -e 'href="BI\|href="MI\|href="PI' | cut -d'"' -f8 | cut -d'/' -f1 > codes.txt

# counts how many codes there are
LN=$(cat codes.txt | wc -l)

# loops through all the codes, makes directories and index file in each
for ((i = 1 ; i <= $LN ; i++))
do
	CURNAME=$( cat codes.txt | head -$i | tail -n1 )
	mkdir "$CURNAME"
	
	cd "$CURNAME"
	echo "===== $CURNAME =====" > index
	cd ..
done

# grabs the date
touch info
DATE=$(wget https://gitlab.fit.cvut.cz/barinkl/bi-ps2-public/raw/master/edux/index.html -q -O - | grep -e 'href="BI\|href="MI\|href="PI' | head -1 | cut -d'>' -f 10 | cut -d' ' -f1)

# saves parts of date
YEAR=$(echo $DATE | cut -d'-' -f1 | cut -c 3-)
MONTH=$(echo $DATE | cut -d'-' -f2)

# sets month to semester
if [[ $MONTH -gt 3 ]]
then
	MONTH='2'
else
	MONTH='1'
fi

# saving of value to info
echo "B$YEAR$MONTH" > info

# cleanup
rm codes.txt

# uncomment to only ls the content of coursesFile and rm everything after
# ls && cd .. && rm -r coursesFile
