#!/usr/bin/env -S awk -f
BEGIN{
    O=0;
    I=0;
    U=0;
    T=0;
    H=0;
}

{
    switch( $3 ){
    case "O:":
        O=$4
        break
    case "I:":
        I=$4
        break
    case "U:":
        U=$4
        break
    case "T:":
        T=$4
        break
    case "heat":
        if($4 == "on")
        {
            H=1;
        }else if($4 == "off")
        {
            H=0;
        }else break;
        match($1, /\[([[:digit:]]{2})\/([[:digit:]]{2})\/([[:digit:]]{4})-(.+)\]/, date);
        print "[", date[3], "/", date[2], "/", date[1], "-", date[4], "]", O, I, U, T, H; 
    default:
        break;
    }
}